# Generated by Django 3.1 on 2020-10-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Upload',
        ),
    ]
