# Generated by Django 3.1 on 2020-11-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_comment_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
